spring.application.name=backend

# í¬í¸ë²í¸ ì¤ì 
server.port=8079

# postë°©ì ì¸ì½ë© ì¤ì 
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# DB설정
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://project-db-campus.smhrd.com:3312/Feely_DB
#spring.datasource.username=cd_26K_HI1_p2_2
#spring.datasource.password=smhrd2

# JPAì¤ì 
# ê°ë°ëì¤ ì»¬ë¼ì´ ì¶ê°ëë¤ê±°ë, ì ì½ì¡°ê±´ì´ ì¶ê°ëë¤ê±°ë í  ë
# ê°±ì ëì¼íê¸° ëë¬¸ì update
spring.jpa.hibernate.ddl-auto=update

#SQL ì¿¼ë¦¬ë¬¸ ì½ìì°½ì ë³´ì´ê² íê¸°
#ì¿¼ë¦¬ë¬¸ ê°ëì± í¥ì
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true