spring.application.name=backend

server.port=8079

# post
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# DB설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://project-db-campus.smhrd.com:3312/cd_26K_HI1_p2_2
spring.datasource.username=cd_26K_HI1_p2_2
spring.datasource.password=smhrd2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 카카오 로그인
kakao.rest-api-key=a491cefda2746a648f3e8498014f7c12
kakao.redirect-uri=http://localhost:4000/Feely/Login/kakao/callback
